### ISSUE TITLE
Hyperlink link (and possibly other) CSS look/feel issues.

### ISSUE THREAD

**Issue by coobr01** [Eastern-Research-Group/lew#100]
**Change Agent Contact Information**
Brad Cooper

**Is this an emergency change request?**
No

**Does the request impact the security posture of the application/system? Please note, if so, the application's ISSO will need to be involved. The current application ISSO is listed in the CMP.**
No

**Describe the change**
Something changed with the One EPA Template (maybe due to Drupal 8 migration) that is causing display issues with at least hyperlink styling. Beside fixing this, please make sure no other CSS issues look to be happening, no network issues or other console error messages.

![image](https://user-images.githubusercontent.com/1842830/148106120-e33b2536-b1a3-4864-83cb-2ef039245a80.png)

**Comment by cschwinderg** [comment]
@coobr01 We have CSS that is trying to force those links to always be black. Do we want these links to be black or just have normal link colors (i.e., blue = unvisited and purple = visited)? 

To me it seems like we would want them to have normal link colors, but I figured I would ask since there is code explicitly making the links black.

**Comment by coobr01** [comment]
@cschwinderg  I don't have an exact answer but to say want to to confirm to the One EPA Template :)

**Comment by coobr01** [comment]
Previously fixed.
